"""Add Document file upload

Revision ID: 06c1c7363fb6
Revises: 
Create Date: 2023-10-29 00:54:09.786756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c1c7363fb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_model', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
