"""+ document tablename

Revision ID: 95fec1c9ab53
Revises: 
Create Date: 2023-10-30 10:11:09.148247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fec1c9ab53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_model',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('author_id', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], name='fk_document_model_author_id_user_table'),
    sa.PrimaryKeyConstraint('id', name='pk_document_model'),
    sa.UniqueConstraint('id', name='uq_document_model_id')
    )
    # ### end Alembic commands ###
