name: Push docker image to prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-build:
    if: contains('["caffeine-addictt"]', github.actor)
    name: Publish docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to docker
        run: |
          docker login --username caffeine-addictt --password ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} ghcr.io
      
      - name: Build image
        run: |
          docker build . --tag ghcr.io/caffeine-addictt/edutecx-build:latest

      - name: Push image
        run: |
          docker push ghcr.io/caffeine-addictt/edutecx-build:latest
  

  trigger-redeploy:
    if: contains('["caffeine-addictt"]', github.actor)
    needs: publish-build
    name: Trigger production deployment
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt install -y curl
      
      - name: Trigger deployment
        run: |
          curl ${{ secrets.REDEPLOY_ENDPOINT }}
